controllers_front:
    resource: ../../src/Controller/Front
    type: annotation
    name_prefix: 'front_'

controllers_admin:
    resource: ../../src/Controller/Admin
    type: annotation
    prefix: '/admin'
    name_prefix: 'admin_'

controllers_dashboard:
    resource: ../../src/Controller/Dashboard
    type: annotation
    prefix: '/dashboard'
    name_prefix: 'dashborad_'


controllers:
    resource: ../../src/Controller
    type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: annotation

