# controllers_front:
#     resource: ../../src/Controller/Front
#     type: annotation
#     name_prefix: 'front_'

# controllers_back:
#     resource: ../../src/Controller/Back
#     type: annotation
#     prefix: '/admin'
#     name_prefix: 'admin_'

# controllers_dashboard:
#     resource: ../../src/Controller/Dashborad
#     type: annotation
#     prefix: '/dashboard'
#     name_prefix: 'dashborad_'


controllers:
    resource: ../../src/Controller
    type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: annotation

